#application name
spring:
  application:
    name: share-lift
  thymeleaf: #thymeleaf配置
    suffix: .html
    encoding: utf-8
    cache: false
  servlet: #文件上传配置
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://129.204.240.8:3306/huyuhao?useSSL=false&serverTimezone=UTC
    initial-size: 10
    max-active: 20
    min-idle: 5
    max-wait: 10000
    filter:
      stat:
        enabled: true
        slow-sql-millis: 1000
        merge-sql: true
        log-slow-sql: true
      wall:
        config:
          multi-statement-allow: true
  #config redis
  redis:
    host: 129.204.240.8
    port: 6379
    password: 123456
    database: 0
    jedis:
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 5
  #config redis

#config server
server:
  port: 8080
  servlet:
    context-path: /share

logging:
  level:
    com.dm.mapper: debug

#config mybatis
mybatis:
  type-aliases-package: com.dm.**.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapper/**/*Mapper.xml

#config shiro
#config druid datasource(native)