#config druid datasource(native)
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/huyuhao?useSSL=false&serverTimezone=UTC
      initial-size: 10
      max-active: 20
      min-idle: 5
      max-wait: 10000
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          merge-sql: true
          log-slow-sql: true
        wall:
          config:
            multi-statement-allow: true
  #config redis
  redis:
    host: 127.0.0.1
    password: 123456
    database: 0
    jedis:
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 5
#config redis